# n.Solve - SLA Monitor Configuration
# Cron Trigger para verificação diária de violações de SLA

name = "sla-monitor"
main = "workers/sla-monitor/index.ts"
compatibility_date = "2024-01-15"

# Cron Trigger - Executa diariamente às 9h AM UTC (6h AM BRT)
[triggers]
crons = ["0 9 * * *"]

# D1 Database
[[d1_databases]]
binding = "VLM_DB"
database_name = "ness-vlm-db"
database_id = "9b8306ff-56a5-4395-bdf5-6a9c001be368"

# Environment variables (opcional - pode usar secrets)
[vars]
# SLACK_WEBHOOK_URL será configurado via secret
# PAGERDUTY_API_KEY será configurado via secret

# Workers dev habilitado para testes
workers_dev = true

