# n.Solve - Wrangler Configuration
# Deploy Manual via CLI (contorna GitHub Auth)

compatibility_date = "2024-01-15"

# Environment variables
[vars]
CORE_PROCESSOR_URL = "https://core-processor.workers.dev"
TRANSLATION_AGENT_URL = "https://translation-agent.workers.dev"
JIRA_INTEGRATION_URL = "https://jira-integration.workers.dev"

# D1 Database
[[d1_databases]]
binding = "VLM_DB"
database_name = "ness-vlm-db"
database_id = "9b8306ff-56a5-4395-bdf5-6a9c001be368"

# R2 Storage
[[r2_buckets]]
binding = "VLM_STORAGE"
bucket_name = "ness-vlm-storage"

# AI (Workers AI)
[ai]
binding = "AI"

# KV Namespace for rate limiting
[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "f89200c908114f39bdb44e55f0244be3"

# KV Namespace for cache
[[kv_namespaces]]
binding = "NESS_VLM_CACHE"
id = "9b00c1feca51468f8a19d110bda74356"