# n.Solve - Wrangler Configuration
# Deploy Manual via CLI (contorna GitHub Auth)

compatibility_date = "2024-01-15"

# Environment variables
[vars]
CORE_PROCESSOR_URL = "https://core-processor.workers.dev"
TRANSLATION_AGENT_URL = "https://translation-agent.workers.dev"
JIRA_INTEGRATION_URL = "https://jira-integration.workers.dev"

# D1 Database
[[d1_databases]]
binding = "VLM_DB"
database_name = "ness_vlm_db"
database_id = "your-database-id-here"

# R2 Storage
[[r2_buckets]]
binding = "VLM_STORAGE"
bucket_name = "ness-vlm-storage"

# AI (Workers AI)
[ai]
binding = "AI"

# KV Namespace for rate limiting
[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "your-kv-namespace-id-here"

# Worker 1: Webhook Receiver
[[workers]]
name = "webhook-receiver"
main = "workers/webhook-receiver/index.ts"
compatibility_date = "2024-01-15"

# Worker 2: Core Processor
[[workers]]
name = "core-processor"
main = "workers/core-processor/index.ts"
compatibility_date = "2024-01-15"

# Worker 3: Translation Agent
[[workers]]
name = "translation-agent"
main = "workers/translation-agent/index.ts"
compatibility_date = "2024-01-15"

# Worker 4: Jira Integration
[[workers]]
name = "jira-integration"
main = "workers/jira-integration/index.ts"
compatibility_date = "2024-01-15"