#:schema node_modules/wrangler/config-schema.json
name = "duplicate-cleanup-agent"
main = "index.ts"
compatibility_date = "2024-01-01"

# Cron Trigger: Executa diariamente às 3:00 AM UTC
[triggers]
crons = ["0 3 * * *"]

# D1 Database Binding
[[d1_databases]]
binding = "VLM_DB"
database_name = "ness_vlm_db"
database_id = "9b16f85c-715e-4a09-aa7e-482b17d0c208"

# Custom domain route
[[routes]]
pattern = "duplicate-cleanup.ness.tec.br/*"
zone_name = "ness.tec.br"

